[tox]
requires =
    tox-uv>=1.16.0
envlist =
    py{310,311,312,313,314}-django52

[testenv]
runner = uv-venv-runner
# This pulls in gcs, s3, and azure extras from [project.optional-dependencies]
extras =
    gcs
    s3
    azure

# This pulls in the 'test' group from [dependency-groups]
dependency_groups =
    test

# Force the Django LTS version
deps =
    django>=5.2,<5.3

passenv = *
allowlist_externals =
    mkdir
commands =
    mkdir -p path/to /var/files/extracted
    pytest -vrx {posargs}
